[METADATA]
modified = 2021-06-18T00:00:00.000Z

[[VALIDATORS]]
network = "main"
owner_country = "us"
server_country = "us"
unl = "https://vl.ripple.com"

[[VALIDATORS]]
network = "testnet"
owner_country = "us"
server_country = "us"
unl = "https://vl.testnet.rippletest.net"

[[ACCOUNTS]]
address = "rGJTFYUudEBKHc5C47996kVdCFjUo83wNm"
desc = "XUM MainOwner"

[[SERVERS]]
json_rpc = "https://s1.ripple.com:51234/"
ws = "wss://s1.ripple.com/"
peer = "https://s1.ripple.com:51235/"
desc = "General purpose server cluster"

[[SERVERS]]
json_rpc = "https://s2.ripple.com:51234/"
ws = "wss://s2.ripple.com/"
peer = "https://s2.ripple.com:51235/"
desc = "Full-history server cluster"

[[SERVERS]]
json_rpc = "https://s.testnet.rippletest.net:51234/"
ws = "wss://s.testnet.rippletest.net:51233/"
peer = "https://s.testnet.rippletest.net:51235/"
network = "testnet"
desc = "Test Net public server cluster"

[[PRINCIPALS]]
name = "V.S.Naaviinesh"
email = "naaviinesh.v.s@gmail.com" 
twitter ="V.S.Naaviinesh"
facebook="V.S. Naaviinesh"
url="https://r5zwe-fqaaa-aaaad-qafxq-cai.ic.fleek.co/"

[[CURRENCIES]]
code = "XVM"
issuer = "rnMAHMtRuGg483Xo4r6XJjrifpm7ukAGaE"
network = "main"
display_decimals = 2
symbol = "https://images.pexels.com/photos/8379294/pexels-photo-8379294.png?auto=compress&cs=tinysrgb&dpr=3&h=30&w=50.4" 
owner_country = "myr"
# End of file